services:
  app:
    container_name:
      django
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py loaddata fixtures.json &&
             python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgis/postgis:15-3.3
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
