# Generated by Django 5.1.5 on 2025-01-26 22:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anemometers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WindSpeedReadings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "speed",
                    models.FloatField(
                        help_text="speed in knots",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "anemometer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wind_readings",
                        to="anemometers.anemometer",
                    ),
                ),
            ],
        ),
    ]
